export const QUERY_KEYS = {
  POKEMON: 'POKEMON',
  POKEMONS: 'POKEMON-FETCH',
  SPECIES: 'POKEMON-SPECIES',
  WEAKNESS: 'POKEMON-WEAKNESS',
  MOVES: 'POKEMON-MOVES',
  ABILITIES: 'POKEMON-ABILITIES',
};
